before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev
    - git clone https://github.com/eigenteam/eigen-git-mirror
language: python
python: 
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt
    - pip install .
script:
    - pytest tests/
branches:
    only:
    - master
